site.settings = {
    // Variables with the path from the root directory of the project
    // to where the site will be read and output
    inputPath: './',
    outputPath: './public/',

    // These urls will replace '~/' in any links you use.
    // This way you can link dynamically for testing and deployment.
    developmentUrl: '/',
    productionUrl: '/ssc-start/',
    baseUrl: 'kaw2k.github.com', // Not needed?

    // This flag will trim the .html out of links that are automatically
    // generated by ssc. This should be used in conjunction with an
    // htaccess file
    trimHTML: false,

    // Add any custom folders to this array i.e. "videos/"
    // Defaults include posts, and pages
    inputFolders: [],

    // The branch your source files are in, defaults to 'source'
    developmentBranch: 'source',

    // The branch your production files are in, defaults to 'master'
    productionBranch: 'gh-pages'
}

// If you want to tack on any other information or functions
// to the site object, you can do so here.
