site.settings = {
    // Variables to help with project and site links. If you are hosting
    // your site out of the root of your domain, these should be fine as is
    sitePathAbs: './',
    sitePathRel: './public/',
    rootPathAbs: './',
    rootPathRel: './',

    // This flag will trim the .html out of links that are automatically
    // generated by ssc. This should be used in conjunction with an
    // htaccess file
    trimHTML: false,

    // Add any custom folders to this array i.e. "videos/"
    inputFolders: [],

    // The branch your source files are in, defaults to 'source'
    devBranch: 'source',

    // The branch your production files are in, defaults to 'master'
    depBranch: 'master'
}
